### PR TITLE
Add xgboost in python

### PR DESCRIPTION
**Pull request by aisensiy**

### CODE REVIEW

**Comment by aisensiy** [comment]
`xgboost` is as common use as `scikit-learn`, so I add it into the `python` module.

**Comment by aisensiy** [comment]
Is this pr acceptable? Or what is your opinion for this?

**Comment by ufoym** [comment]
The following PRs are more preferable:
- deep learning modules
- tools on which those modules depend
- tools on which building those modules depend

`xgboost`, of course, is excellent and commonly used in ML field. However, to keep `deepo` slim (we know, we know, `deepo` is actually too fat currently), we suggest installing `xgboost` on top of `deepo` image.

**Comment by aisensiy** [comment]
Yes, I understand your concern. Maybe make it as a separate module is better.

And actually, in my opinion, `deepo` is **QUITE** slim as a deep learning environment images. Look around for any other images with similar use cases (like [floydhub/tensorflow](http://hub.docker.com/r/floydhub/tensorflow)). It is much bigger than `deepo`.

**Pull request closed without merging**
